[WIP] OSIS-4082 migration to handle perms with Osis Role
uclouvain/osis-continuing-education pull request #411
Opened 2020-03-26 10:56 UTC by mathieuzen

2021-04-26 11:21 UTC, albrugnetti commented on auth/predicates.py
> +def is_training_manager(self, user, training):
Est-ce qu'il ne faut pas être plus généralise: 
"**is_user_linked_to_training(user, training)**" ?

2021-04-26 11:21 UTC, albrugnetti commented on auth/predicates.py
> +def is_admission_training_manager(self, user, admission):
Est-ce qu'il ne faut pas être plus généralise:
"is_user_linked_to_admission(user, admission)" ?

2021-04-26 11:21 UTC, albrugnetti commented on auth/predicates.py
> +def is_prospect_training_manager(self, user, prospect):
Est-ce qu'il ne faut pas être plus généralise:
"is_user_linked_to_prospect(user, admission)" ?

2021-04-26 11:21 UTC, albrugnetti commented on auth/roles/continuing_education_manager.py
> +    return user.groups.filter(name=MANAGERS_GROUP).exists()
Je ne comprends l'utilité de ces fonctions? Dans la mesure où les prédicats pertinents vont être vérifiés aux moments du check d'une permission?

2021-04-26 11:21 UTC, albrugnetti commented on auth/roles/continuing_education_student_worker.py
> +    return user.groups.filter(name=STUDENT_WORKERS_GROUP).exists()
idem?

2021-04-26 11:21 UTC, albrugnetti commented on auth/roles/continuing_education_training_manager.py
> +    return user.groups.filter(name=TRAINING_MANAGERS_GROUP).exists()
Idem?

2021-04-26 11:21 UTC, albrugnetti commented on locale/fr_BE/LC_MESSAGES/django.po
> +#~ msgstr "Vous n'êtes pas autorisé à modifier cette formation"
N'oublie pas de supprimer

2021-04-26 11:21 UTC, albrugnetti commented on models/admission.py
> +    return get_object_or_none(Admission, id=view_kwargs.get('admission_id'))
[_Optionnel_]  Est-ce qu'il faut faire un select_related/prefetch_related pour les prédicats? Ou pas necessaire?

2021-04-26 11:21 UTC, albrugnetti commented on views/admission.py
> +@permission_required('continuing_education.export_admission', raise_exception=True)
Est-ce que c'est logique d'avoir cette permission dans la vue "**list_admissions**" ?

2021-04-26 11:21 UTC, albrugnetti commented on views/admission.py
> +                     raise_exception=True)
Pourquoi tu n'utilies pas la fonction **admission_getter**

2021-04-26 11:21 UTC, albrugnetti commented on views/admission.py
> +    fn=objectgetter(Admission, 'admission_id'),
Pourquoi tu n'utilises pas la fonction **admission_getter**

2021-04-26 11:21 UTC, albrugnetti commented on views/admission.py
> +@permission_required('continuing_education.change_admission', fn=objectgetter(Admission, 'admission_id'),
Idem pourquoi, tu n'utilises pas la fonction **admission_getter**

2021-04-26 11:21 UTC, albrugnetti commented on views/archive.py
> +@permission_required('continuing_education.archive_admission', raise_exception=True)
Pourquoi ne pas avoir une permission "**view_admission_archives**" ?

2021-04-26 11:21 UTC, albrugnetti commented on views/archive.py
> +@permission_required('continuing_education.export_admission')
Pourquoi ne pas avoir une permission "export_admission_archives" ?

2021-04-26 11:21 UTC, albrugnetti commented on views/registration.py
> +def export_registrations(request, admission_list, search_form):
Le nom de la permission est assez différent du nom de l'action, est-ce que c'est voulu ?

2021-04-26 13:47 UTC, mathieuzen commented on auth/roles/continuing_education_manager.py
> +    return user.groups.filter(name=MANAGERS_GROUP).exists()
c'est pour construire le contexte utilisé par le template
https://github.com/uclouvain/osis-continuing-education/blob/86d48d329d495d487a157b6c7e364e957571fd26/views/home.py#L37

2021-04-26 13:47 UTC, mathieuzen commented on auth/roles/continuing_education_student_worker.py
> +    return user.groups.filter(name=STUDENT_WORKERS_GROUP).exists()
idem

2021-04-26 13:56 UTC, mathieuzen commented on views/registration.py
> +def export_registrations(request, admission_list, search_form):
oui car au final une inscription est une admission dans un état particulier

2021-04-27 07:53 UTC, albrugnetti approved these changes

2021-04-27 11:36 UTC, matgerard requested changes

2021-04-27 11:36 UTC, matgerard commented on templates/fragment/tab_documents.html
> +                        <a class="button download" role="button" title="{% trans 'Download document' %}"
Idem ?

2021-04-27 11:36 UTC, matgerard commented on views/admission.py
> +    if request.GET.get('xls_status') == "xls_admissions":
Ce if est dupliqué du coup (ici et ligne 85)

2021-04-27 11:36 UTC, matgerard commented on views/admission.py
> +        elif cannot_validate_registration and registration_is_submitted or registration_is_validated:
Je serais explicite dans la priorité des opérateurs booléens : 
`cannot_validate_registration and (registration_is_submitted or registration_is_validated)`

2021-04-27 11:41 UTC, mathieuzen commented on templates/blocks/button/xls.html
> +   class="download"
justement à la base j'avais une PR pour corriger ça, il fallait seulement attendre que osis-common soit update en qa à l'époque (et ce n'était pas encore le cas), depuis le temps osis-common a été mis à jour... 
J'ai testé en local ça semble fonctionner correctement, je testerai à nouveau sur branche déployée avec chrome/firefox pour être sûr.

2021-04-27 11:41 UTC, mathieuzen commented on templates/fragment/tab_documents.html
> +                        <a class="button download" role="button" title="{% trans 'Download document' %}"
idem

2021-04-27 12:42 UTC, matgerard approved these changes

2021-04-27 12:49 UTC, merged