IUFC-726 Filter prospects list and xls by manager's trainings
uclouvain/osis-continuing-education pull request #491
Opened 2021-08-19 13:08 UTC by matgerard

IUFC-726

2021-08-19 13:58 UTC, BenJneB approved these changes

2021-08-19 14:51 UTC, mathieuzen requested changes

2021-08-19 14:51 UTC, mathieuzen commented on templates/prospects.html
> +                           title="Produce xls" class="no_spinner">
je pense que le problème du spinner qui ne disparaît pas pour les téléchargements de fichiers avait été réglé, essaie avec class="download"

2021-08-19 14:51 UTC, mathieuzen commented on templates/prospects.html
> +                           title="Produce xls" class="no_spinner">
j'ai retrouvé les autres cas similaires, il faut également ajouter le décorateur @set_download_cookie sur la vue qui exporte le fichier (prospects.create_xls ici j'imagine ?)

2021-08-24 12:31 UTC, mathieuzen approved these changes

2021-08-24 13:29 UTC, merged