[DEV] Django32
uclouvain/osis-continuing-education pull request #548
Opened 2022-04-01 12:18 UTC by edd19

2022-04-01 12:43 UTC, BenJneB commented on tests/views/test_registration.py
> +    @skip("This test send wrong post data")
Pourquoi ce skip ? Le test passe en local

2022-04-01 12:45 UTC, mathieuzen requested changes

2022-04-01 12:45 UTC, mathieuzen commented on tests/views/test_registration.py
> +    @skip("This test send wrong post data")
pourquoi ce test doit être skip, il passe localement

2022-04-04 06:38 UTC, edd19 commented on tests/views/test_registration.py
> +    @skip("This test send wrong post data")
Quand je le teste en local (en mode parallèle), le teste ne pase pas. 
Je teste en django 3.2.
Aussi, le test en lui-même n'est pas lisible.

2022-04-04 12:46 UTC, closed without merging